### ISSUE TITLE
More Bugs

### ISSUE THREAD

**Issue by zitrusblau** [sloyer/WPBaseFoundation#2]
It seems my praise was to hasty! :(

In this case what is the purpose of the entry.php? With the new query which is limited to 3 posts we'll get an archive page which iterative list only the latest 3 posts.

This is really nonsense!

Also the Foundation Framework is construed for html 5 documents, but in the theme a doctype is completely missing and the html 5 tags you've used are really spartan.
I think it will make a lot of work to make this theme a valid and well coded html 5 theme, it's a shame!

**Comment by sloyer** [comment]
Hey zitrusblau, 

I have been busy on other projects for work and haven't had time to even check into this. 
You are absolutely correct with your thoughts.

The first reason with entry being limited to 3 was probably back to a site I originally made this for. It was probably something that got carried over by accident. 

The second thing is yes, Foundation is meant to be with HTML5. Really this theme you are really suppose to gut (what little is there) it and just use the tools it comes with and write your own code. 

I have slowly been working on a new version of this theme for a whole new release with a bunch of extra mixins and function goodies. 

I was actually waiting for Foundation 6 to come out before I did this but we have just been contracted for a few builds and for those builds I was going to go back through this all.
